"""
Unit tests for User Data Access Layer.

Tests CRUD operations for users independently from Flask routes.
"""
# AI Contribution: Test patterns generated by Cursor AI; team added edge cases

import pytest
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.data_access.user_dal import UserDAL
from src.models.database import init_database, get_db_connection


@pytest.fixture
def test_db():
    """Create a test database before each test and clean up after."""
    # Initialize test database
    init_database()
    yield
    # Cleanup
    conn = get_db_connection()
    conn.execute("DELETE FROM users")
    conn.commit()
    conn.close()


def test_create_user(test_db):
    """Test user creation with password hashing."""
    user_id = UserDAL.create_user(
        name="Test User",
        email="test@example.com",
        password="password123",
        role="student",
        department="Computer Science"
    )
    
    assert user_id is not None
    assert user_id > 0
    
    # Verify user was created
    user = UserDAL.get_user_by_id(user_id)
    assert user is not None
    assert user['name'] == "Test User"
    assert user['email'] == "test@example.com"
    assert user['role'] == "student"
    # Password should be hashed, not plain text
    assert user['password_hash'] != "password123"


def test_get_user_by_email(test_db):
    """Test retrieving user by email address."""
    UserDAL.create_user(
        name="John Doe",
        email="john@example.com",
        password="secret123",
        role="student"
    )
    
    user = UserDAL.get_user_by_email("john@example.com")
    assert user is not None
    assert user['name'] == "John Doe"
    
    # Non-existent email should return None
    user = UserDAL.get_user_by_email("nonexistent@example.com")
    assert user is None


def test_verify_password(test_db):
    """Test password verification."""
    UserDAL.create_user(
        name="Jane Smith",
        email="jane@example.com",
        password="correct_password",
        role="staff"
    )
    
    # Correct password should verify
    user = UserDAL.verify_password("jane@example.com", "correct_password")
    assert user is not None
    assert user['email'] == "jane@example.com"
    
    # Incorrect password should not verify
    user = UserDAL.verify_password("jane@example.com", "wrong_password")
    assert user is None
    
    # Non-existent email should not verify
    user = UserDAL.verify_password("nobody@example.com", "any_password")
    assert user is None


def test_update_user(test_db):
    """Test updating user information."""
    user_id = UserDAL.create_user(
        name="Original Name",
        email="update@example.com",
        password="password",
        role="student"
    )
    
    # Update user
    success = UserDAL.update_user(
        user_id,
        name="Updated Name",
        department="Engineering"
    )
    assert success is True
    
    # Verify updates
    user = UserDAL.get_user_by_id(user_id)
    assert user['name'] == "Updated Name"
    assert user['department'] == "Engineering"
    assert user['email'] == "update@example.com"  # Should not change


def test_update_password(test_db):
    """Test password update."""
    user_id = UserDAL.create_user(
        name="Password Test",
        email="pwd@example.com",
        password="old_password",
        role="student"
    )
    
    # Update password
    success = UserDAL.update_password(user_id, "new_password")
    assert success is True
    
    # Old password should not work
    user = UserDAL.verify_password("pwd@example.com", "old_password")
    assert user is None
    
    # New password should work
    user = UserDAL.verify_password("pwd@example.com", "new_password")
    assert user is not None


def test_delete_user(test_db):
    """Test user deletion."""
    user_id = UserDAL.create_user(
        name="Delete Me",
        email="delete@example.com",
        password="password",
        role="student"
    )
    
    # Delete user
    success = UserDAL.delete_user(user_id)
    assert success is True
    
    # User should no longer exist
    user = UserDAL.get_user_by_id(user_id)
    assert user is None


def test_get_user_statistics(test_db):
    """Test user statistics aggregation."""
    # Create users with different roles
    UserDAL.create_user("Student1", "s1@example.com", "pwd", "student")
    UserDAL.create_user("Student2", "s2@example.com", "pwd", "student")
    UserDAL.create_user("Staff1", "staff@example.com", "pwd", "staff")
    UserDAL.create_user("Admin1", "admin@example.com", "pwd", "admin")
    
    stats = UserDAL.get_user_statistics()
    assert stats['total_users'] == 4
    assert stats['students'] == 2
    assert stats['staff'] == 1
    assert stats['admins'] == 1

