"""
WTForms form definitions for Campus Resource Hub.

Provides form classes with validation for all user inputs.
Server-side validation is mandatory for security.
"""
# AI Contribution: Form validation patterns generated by Cursor AI; team added custom validators

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, SelectField, DateTimeField, IntegerField, BooleanField, HiddenField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError, Optional, NumberRange
from datetime import datetime


class RegistrationForm(FlaskForm):
    """User registration form."""
    name = StringField('Full Name', validators=[
        DataRequired(message='Name is required'),
        Length(min=2, max=100, message='Name must be between 2 and 100 characters')
    ])
    email = StringField('Email', validators=[
        DataRequired(message='Email is required'),
        Email(message='Invalid email address'),
        Length(max=120)
    ])
    password = PasswordField('Password', validators=[
        DataRequired(message='Password is required'),
        Length(min=8, message='Password must be at least 8 characters')
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(message='Please confirm your password'),
        EqualTo('password', message='Passwords must match')
    ])
    role = SelectField('Role', choices=[
        ('student', 'Student'),
        ('staff', 'Staff')
    ], validators=[DataRequired()])
    department = StringField('Department', validators=[
        Length(max=100, message='Department name too long')
    ])


class LoginForm(FlaskForm):
    """User login form."""
    email = StringField('Email', validators=[
        DataRequired(message='Email is required'),
        Email(message='Invalid email address')
    ])
    password = PasswordField('Password', validators=[
        DataRequired(message='Password is required')
    ])


class ResourceForm(FlaskForm):
    """Create/Edit resource form."""
    title = StringField('Title', validators=[
        DataRequired(message='Title is required'),
        Length(min=3, max=200, message='Title must be between 3 and 200 characters')
    ])
    description = TextAreaField('Description', validators=[
        Length(max=2000, message='Description too long')
    ])
    category = SelectField('Category', choices=[
        ('', '-- Select Category --'),
        ('Study Room', 'Study Room'),
        ('Meeting Room', 'Meeting Room'),
        ('Equipment', 'Equipment'),
        ('Lab Space', 'Lab Space'),
        ('Event Space', 'Event Space'),
        ('Tutoring', 'Tutoring'),
        ('Other', 'Other')
    ], validators=[DataRequired(message='Please select a category')])
    location = StringField('Location', validators=[
        Length(max=200, message='Location too long')
    ])
    capacity = IntegerField('Capacity', validators=[
        Optional(),
        NumberRange(min=1, max=1000, message='Capacity must be between 1 and 1000')
    ])
    status = SelectField('Status', choices=[
        ('draft', 'Draft'),
        ('published', 'Published'),
        ('archived', 'Archived')
    ], validators=[DataRequired()])
    requires_approval = BooleanField('Requires Approval')


class BookingForm(FlaskForm):
    """Create booking request form."""
    resource_id = HiddenField('Resource ID', validators=[DataRequired()])
    start_datetime = DateTimeField('Start Date & Time', 
                                   format='%Y-%m-%dT%H:%M',
                                   validators=[DataRequired(message='Start time is required')])
    end_datetime = DateTimeField('End Date & Time',
                                 format='%Y-%m-%dT%H:%M',
                                 validators=[DataRequired(message='End time is required')])
    notes = TextAreaField('Notes/Purpose', validators=[
        Length(max=500, message='Notes too long')
    ])
    
    def validate_end_datetime(self, field):
        """Ensure end time is after start time."""
        if field.data and self.start_datetime.data:
            if field.data <= self.start_datetime.data:
                raise ValidationError('End time must be after start time')
            
            # Check if booking is too long (e.g., max 24 hours)
            duration = (field.data - self.start_datetime.data).total_seconds() / 3600
            if duration > 24:
                raise ValidationError('Booking duration cannot exceed 24 hours')


class MessageForm(FlaskForm):
    """Send message form."""
    receiver_id = HiddenField('Receiver ID', validators=[DataRequired()])
    content = TextAreaField('Message', validators=[
        DataRequired(message='Message content is required'),
        Length(min=1, max=1000, message='Message must be between 1 and 1000 characters')
    ])
    booking_id = HiddenField('Booking ID')


class ReviewForm(FlaskForm):
    """Submit review form."""
    resource_id = HiddenField('Resource ID', validators=[DataRequired()])
    booking_id = HiddenField('Booking ID')
    rating = SelectField('Rating', choices=[
        ('5', '⭐⭐⭐⭐⭐ Excellent'),
        ('4', '⭐⭐⭐⭐ Good'),
        ('3', '⭐⭐⭐ Average'),
        ('2', '⭐⭐ Poor'),
        ('1', '⭐ Terrible')
    ], validators=[DataRequired(message='Please select a rating')])
    comment = TextAreaField('Review', validators=[
        Length(max=1000, message='Review too long')
    ])


class SearchForm(FlaskForm):
    """Search resources form."""
    keyword = StringField('Search', validators=[Length(max=100)])
    category = SelectField('Category', choices=[
        ('', 'All Categories'),
        ('Study Room', 'Study Room'),
        ('Meeting Room', 'Meeting Room'),
        ('Equipment', 'Equipment'),
        ('Lab Space', 'Lab Space'),
        ('Event Space', 'Event Space'),
        ('Tutoring', 'Tutoring'),
        ('Other', 'Other')
    ])
    location = StringField('Location', validators=[Length(max=100)])
    sort_by = SelectField('Sort By', choices=[
        ('recent', 'Most Recent'),
        ('rating', 'Top Rated'),
        ('bookings', 'Most Popular')
    ])


class ProfileForm(FlaskForm):
    """Update user profile form."""
    name = StringField('Full Name', validators=[
        DataRequired(message='Name is required'),
        Length(min=2, max=100, message='Name must be between 2 and 100 characters')
    ])
    department = StringField('Department', validators=[
        Length(max=100, message='Department name too long')
    ])


class ChangePasswordForm(FlaskForm):
    """Change password form."""
    current_password = PasswordField('Current Password', validators=[
        DataRequired(message='Current password is required')
    ])
    new_password = PasswordField('New Password', validators=[
        DataRequired(message='New password is required'),
        Length(min=8, message='Password must be at least 8 characters')
    ])
    confirm_password = PasswordField('Confirm New Password', validators=[
        DataRequired(message='Please confirm your new password'),
        EqualTo('new_password', message='Passwords must match')
    ])

